## Binary Sensor
  
- platform: mqtt
    name: "HydraBasic Motion"
    state_topic: "HydraBasic/PIR/state"
    availability_topic: "tele/HydraBasic/LWT"
    qos: 1
    payload_on: "YES"
    payload_off: "NO"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    device_class: motion